@startuml
skinparam nodesep 10
skinparam rectangle {
    backgroundColor<<OV>> 99ccff
    backgroundColor<<CP>> 99ff99
    backgroundColor<<CPS>> d0ebbf
    backgroundColor<<AS>> ffe389
    backgroundColor<<POP>> cdabe7
    backgroundColor<<RI>> e2c4a6
    backgroundColor<<TI>> ffa3a3
}
rectangle "[[Requirements-EHRSFMR2.1-CP.1.1.html CP.1.1]]" <<CP>> as 39
rectangle "[[Requirements-EHRSFMR2.1-CPS.2.1.html CPS.2.1]]" <<CPS>> as 762
39 --> 762
rectangle "[[Requirements-EHRSFMR2.1-CPS.2.2.html CPS.2.2]]" <<CPS>> as 774
39 --> 774
rectangle "[[Requirements-EHRSFMR2.1-CP.1.2.html CP.1.2]]" <<CP>> as 53
rectangle "[[Requirements-EHRSFMR2.1-CPS.4.2.1.html CPS.4.2.1]]" <<CPS>> as 957
53 --> 957
rectangle "[[Requirements-EHRSFMR2.1-CP.1.3.html CP.1.3]]" <<CP>> as 81
81 --> 957
rectangle "[[Requirements-EHRSFMR2.1-CP.1.4.html CP.1.4]]" <<CP>> as 114
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.17.html RI.1.1.17]]" <<RI>> as 2014
114 --> 2014
rectangle "[[Requirements-EHRSFMR2.1-CP.1.5.html CP.1.5]]" <<CP>> as 140
140 --> 2014
rectangle "[[Requirements-EHRSFMR2.1-CP.3.1.html CP.3.1]]" <<CP>> as 199
rectangle "[[Requirements-EHRSFMR2.1-CPS.3.1.html CPS.3.1]]" <<CPS>> as 813
199 --> 813
rectangle "[[Requirements-EHRSFMR2.1-CPS.3.2.html CPS.3.2]]" <<CPS>> as 822
199 --> 822
rectangle "[[Requirements-EHRSFMR2.1-CP.3.4.html CP.3.4]]" <<CP>> as 260
rectangle "[[Requirements-EHRSFMR2.1-CP.7.1.html CP.7.1]]" <<CP>> as 590
260 --> 590
rectangle "[[Requirements-EHRSFMR2.1-AS.5.1.html AS.5.1]]" <<AS>> as 1526
260 --> 1526
rectangle "[[Requirements-EHRSFMR2.1-AS.5.3.html AS.5.3]]" <<AS>> as 1555
260 --> 1555
rectangle "[[Requirements-EHRSFMR2.1-AS.5.4.html AS.5.4]]" <<AS>> as 1560
260 --> 1560
rectangle "[[Requirements-EHRSFMR2.1-CPS.4.2.2.html CPS.4.2.2]]" <<CPS>> as 974
260 --> 974
rectangle "[[Requirements-EHRSFMR2.1-CPS.1.7.1.html CPS.1.7.1]]" <<CPS>> as 728
260 --> 728
rectangle "[[Requirements-EHRSFMR2.1-CP.4.html CP.4]]" <<CP>> as 287
rectangle "[[Requirements-EHRSFMR2.1-CPS.8.4.html CPS.8.4]]" <<CPS>> as 1133
287 --> 1133
rectangle "[[Requirements-EHRSFMR2.1-CP.4.1.html CP.4.1]]" <<CP>> as 315
rectangle "[[Requirements-EHRSFMR2.1-CPS.4.1.html CPS.4.1]]" <<CPS>> as 920
315 --> 920
rectangle "[[Requirements-EHRSFMR2.1-CP.4.2.html CP.4.2]]" <<CP>> as 327
rectangle "[[Requirements-EHRSFMR2.1-CP.4.2.1.html CP.4.2.1]]" <<CP>> as 373
327 --> 373
rectangle "[[Requirements-EHRSFMR2.1-CP.4.2.2.html CP.4.2.2]]" <<CP>> as 379
327 --> 379
rectangle "[[Requirements-EHRSFMR2.1-CP.4.2.3.html CP.4.2.3]]" <<CP>> as 393
327 --> 393
rectangle "[[Requirements-EHRSFMR2.1-CP.4.2.4.html CP.4.2.4]]" <<CP>> as 402
327 --> 402
327 --> 81
rectangle "[[Requirements-EHRSFMR2.1-CPS.4.2.4.html CPS.4.2.4]]" <<CPS>> as 1007
327 --> 1007
rectangle "[[Requirements-EHRSFMR2.1-AS.9.2.html AS.9.2]]" <<AS>> as 1675
327 --> 1675
373 --> 957
373 --> 53
379 --> 974
393 --> 315
rectangle "[[Requirements-EHRSFMR2.1-CP.4.3.html CP.4.3]]" <<CP>> as 406
rectangle "[[Requirements-EHRSFMR2.1-CPS.4.3.html CPS.4.3]]" <<CPS>> as 1015
406 --> 1015
rectangle "[[Requirements-EHRSFMR2.1-CP.4.4.html CP.4.4]]" <<CP>> as 416
416 --> 1015
rectangle "[[Requirements-EHRSFMR2.1-CP.4.5.html CP.4.5]]" <<CP>> as 429
rectangle "[[Requirements-EHRSFMR2.1-CPS.9.2.html CPS.9.2]]" <<CPS>> as 1173
429 --> 1173
rectangle "[[Requirements-EHRSFMR2.1-CP.6.1.html CP.6.1]]" <<CP>> as 489
489 --> 957
489 --> 974
rectangle "[[Requirements-EHRSFMR2.1-CP.6.2.html CP.6.2]]" <<CP>> as 530
rectangle "[[Requirements-EHRSFMR2.1-CP.3.2.html CP.3.2]]" <<CP>> as 219
530 --> 219
530 --> 53
rectangle "[[Requirements-EHRSFMR2.1-CP.1.6.html CP.1.6]]" <<CP>> as 151
530 --> 151
rectangle "[[Requirements-EHRSFMR2.1-CP.6.3.html CP.6.3]]" <<CP>> as 553
553 --> 489
553 --> 53
553 --> 219
rectangle "[[Requirements-EHRSFMR2.1-CPS.1.7.html CPS.1.7]]" <<CPS>> as 726
553 --> 726
rectangle "[[Requirements-EHRSFMR2.1-CPS.3.8.html CPS.3.8]]" <<CPS>> as 876
590 --> 876
rectangle "[[Requirements-EHRSFMR2.1-CPS.3.4.html CPS.3.4]]" <<CPS>> as 846
590 --> 846
rectangle "[[Requirements-EHRSFMR2.1-CP.9.2.html CP.9.2]]" <<CP>> as 623
rectangle "[[Requirements-EHRSFMR2.1-CP.9.1.html CP.9.1]]" <<CP>> as 621
623 --> 621
rectangle "[[Requirements-EHRSFMR2.1-CP.1.html CP.1]]" <<CP>> as 38
rectangle "[[Requirements-EHRSFMR2.1-CPS.1.html CPS.1]]" <<CPS>> as 631
38 -[dotted]-> 631
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.21.html RI.1.1.21]]" <<RI>> as 2068
114 -[dotted]-> 2068
rectangle "[[Requirements-EHRSFMR2.1-CP.1.7.html CP.1.7]]" <<CP>> as 158
114 -[dotted]-> 158
rectangle "[[Requirements-EHRSFMR2.1-CP.1.4.html CP.1.4#11]]" <<CP>> as 124
124 -[dotted]-> 2068
rectangle "[[Requirements-EHRSFMR2.1-CP.1.4.html CP.1.4#12]]" <<CP>> as 125
125 -[dotted]-> 2068
rectangle "[[Requirements-EHRSFMR2.1-CP.1.4.html CP.1.4#13]]" <<CP>> as 126
126 -[dotted]-> 2068
rectangle "[[Requirements-EHRSFMR2.1-CP.1.4.html CP.1.4#14]]" <<CP>> as 127
127 -[dotted]-> 2068
127 -[dotted]-> 158
rectangle "[[Requirements-EHRSFMR2.1-CP.1.4.html CP.1.4#15]]" <<CP>> as 128
128 -[dotted]-> 2068
128 -[dotted]-> 158
rectangle "[[Requirements-EHRSFMR2.1-CP.1.4.html CP.1.4#16]]" <<CP>> as 129
129 -[dotted]-> 2068
rectangle "[[Requirements-EHRSFMR2.1-CP.1.4.html CP.1.4#17]]" <<CP>> as 130
130 -[dotted]-> 158
140 -[dotted]-> 114
rectangle "[[Requirements-EHRSFMR2.1-CP.2.html CP.2]]" <<CP>> as 181
rectangle "[[Requirements-EHRSFMR2.1-CPS.2.html CPS.2]]" <<CPS>> as 759
181 -[dotted]-> 759
rectangle "[[Requirements-EHRSFMR2.1-CP.2.1.html CP.2.1]]" <<CP>> as 183
183 -[dotted]-> 762
rectangle "[[Requirements-EHRSFMR2.1-CP.2.2.html CP.2.2]]" <<CP>> as 185
185 -[dotted]-> 774
rectangle "[[Requirements-EHRSFMR2.1-CP.2.3.html CP.2.3]]" <<CP>> as 187
rectangle "[[Requirements-EHRSFMR2.1-CPS.2.3.html CPS.2.3]]" <<CPS>> as 783
187 -[dotted]-> 783
rectangle "[[Requirements-EHRSFMR2.1-CP.2.4.html CP.2.4]]" <<CP>> as 189
rectangle "[[Requirements-EHRSFMR2.1-CPS.2.4.html CPS.2.4]]" <<CPS>> as 786
189 -[dotted]-> 786
rectangle "[[Requirements-EHRSFMR2.1-CP.2.5.html CP.2.5]]" <<CP>> as 191
rectangle "[[Requirements-EHRSFMR2.1-CPS.2.5.html CPS.2.5]]" <<CPS>> as 790
191 -[dotted]-> 790
rectangle "[[Requirements-EHRSFMR2.1-CP.3.html CP.3]]" <<CP>> as 198
rectangle "[[Requirements-EHRSFMR2.1-CPS.3.html CPS.3]]" <<CPS>> as 812
198 -[dotted]-> 812
rectangle "[[Requirements-EHRSFMR2.1-CP.3.3.html CP.3.3#05]]" <<CP>> as 242
242 -[dotted]-> 114
rectangle "[[Requirements-EHRSFMR2.1-CP.3.3.html CP.3.3#06]]" <<CP>> as 243
243 -[dotted]-> 114
rectangle "[[Requirements-EHRSFMR2.1-CPS.4.html CPS.4]]" <<CPS>> as 919
287 -[dotted]-> 919
rectangle "[[Requirements-EHRSFMR2.1-CP.4.6.html CP.4.6]]" <<CP>> as 437
rectangle "[[Requirements-EHRSFMR2.1-CPS.1.4.html CPS.1.4]]" <<CPS>> as 676
437 -[dotted]-> 676
rectangle "[[Requirements-EHRSFMR2.1-CP.5.html CP.5]]" <<CP>> as 450
rectangle "[[Requirements-EHRSFMR2.1-CPS.5.html CPS.5]]" <<CPS>> as 1063
450 -[dotted]-> 1063
rectangle "[[Requirements-EHRSFMR2.1-CP.6.html CP.6]]" <<CP>> as 488
rectangle "[[Requirements-EHRSFMR2.1-CPS.6.html CPS.6]]" <<CPS>> as 1073
488 -[dotted]-> 1073
rectangle "[[Requirements-EHRSFMR2.1-CP.7.html CP.7]]" <<CP>> as 589
rectangle "[[Requirements-EHRSFMR2.1-CPS.7.html CPS.7]]" <<CPS>> as 1107
589 -[dotted]-> 1107
rectangle "[[Requirements-EHRSFMR2.1-CP.8.html CP.8]]" <<CP>> as 604
rectangle "[[Requirements-EHRSFMR2.1-CPS.8.html CPS.8]]" <<CPS>> as 1117
604 -[dotted]-> 1117
rectangle "[[Requirements-EHRSFMR2.1-CP.9.html CP.9]]" <<CP>> as 620
rectangle "[[Requirements-EHRSFMR2.1-CPS.9.html CPS.9]]" <<CPS>> as 1167
620 -[dotted]-> 1167
rectangle "[[Requirements-EHRSFMR2.1-AS.1.html AS.1]]" <<AS>> as 1395
620 -[dotted]-> 1395
676 --> 762
676 --> 774
676 --> 783
676 --> 786
676 --> 1675
rectangle "[[Requirements-EHRSFMR2.1-AS.6.2.html AS.6.2]]" <<AS>> as 1580
676 --> 1580
726 --> 728
rectangle "[[Requirements-EHRSFMR2.1-CPS.1.7.2.html CPS.1.7.2]]" <<CPS>> as 736
736 --> 786
rectangle "[[Requirements-EHRSFMR2.1-CPS.1.7.3.html CPS.1.7.3]]" <<CPS>> as 745
745 --> 762
745 --> 774
rectangle "[[Requirements-EHRSFMR2.1-TI.1.5.html TI.1.5]]" <<TI>> as 2231
762 --> 2231
813 --> 114
rectangle "[[Requirements-EHRSFMR2.1-CPS.3.3.html CPS.3.3]]" <<CPS>> as 831
rectangle "[[Requirements-EHRSFMR2.1-POP.4.html POP.4]]" <<POP>> as 1325
831 --> 1325
831 --> 846
831 --> 813
846 --> 813
846 --> 822
846 --> 831
rectangle "[[Requirements-EHRSFMR2.1-CPS.3.5.html CPS.3.5]]" <<CPS>> as 857
rectangle "[[Requirements-EHRSFMR2.1-AS.9.1.html AS.9.1]]" <<AS>> as 1670
857 --> 1670
rectangle "[[Requirements-EHRSFMR2.1-CP.3.3.html CP.3.3]]" <<CP>> as 237
857 --> 237
rectangle "[[Requirements-EHRSFMR2.1-CPS.3.6.html CPS.3.6]]" <<CPS>> as 868
868 --> 790
rectangle "[[Requirements-EHRSFMR2.1-CP.1.8.html CP.1.8]]" <<CP>> as 170
868 --> 170
868 --> 114
rectangle "[[Requirements-EHRSFMR2.1-CPS.3.10.html CPS.3.10]]" <<CPS>> as 885
885 --> 199
885 --> 876
885 --> 846
920 --> 315
957 --> 876
957 --> 81
rectangle "[[Requirements-EHRSFMR2.1-CPS.9.2.3.html CPS.9.2.3]]" <<CPS>> as 1201
974 --> 1201
1007 --> 974
rectangle "[[Requirements-EHRSFMR2.1-CPS.4.6.3.html CPS.4.6.3]]" <<CPS>> as 1044
1044 --> 1675
rectangle "[[Requirements-EHRSFMR2.1-CPS.6.1.html CPS.6.1]]" <<CPS>> as 1074
rectangle "[[Requirements-EHRSFMR2.1-CPS.7.1.html CPS.7.1]]" <<CPS>> as 1108
1074 --> 1108
rectangle "[[Requirements-EHRSFMR2.1-CPS.6.2.html CPS.6.2]]" <<CPS>> as 1084
1084 --> 1108
rectangle "[[Requirements-EHRSFMR2.1-CPS.6.3.html CPS.6.3]]" <<CPS>> as 1097
1097 --> 219
1108 --> 831
1201 --> 327
676 -[dotted]-> 437
rectangle "[[Requirements-EHRSFMR2.1-CPS.4.4.html CPS.4.4]]" <<CPS>> as 1027
1027 -[dotted]-> 416
rectangle "[[Requirements-EHRSFMR2.1-CPS.4.5.html CPS.4.5]]" <<CPS>> as 1028
1028 -[dotted]-> 429
rectangle "[[Requirements-EHRSFMR2.1-CPS.4.6.html CPS.4.6]]" <<CPS>> as 1029
1029 -[dotted]-> 437
1044 -[dotted]-> 676
1044 -[dotted]-> 437
1063 -[dotted]-> 450
rectangle "[[Requirements-EHRSFMR2.1-CPS.1.3.html CPS.1.3]]" <<CPS>> as 672
rectangle "[[Requirements-EHRSFMR2.1-CPS.1.1.html CPS.1.1]]" <<CPS>> as 632
672 -[dotted]-> 632
rectangle "[[Requirements-EHRSFMR2.1-AS.1.1.html AS.1.1]]" <<AS>> as 1396
rectangle "[[Requirements-EHRSFMR2.1-TI.3.html TI.3]]" <<TI>> as 2559
1396 --> 2559
rectangle "[[Requirements-EHRSFMR2.1-AS.1.6.html AS.1.6]]" <<AS>> as 1421
rectangle "[[Requirements-EHRSFMR2.1-AS.1.7.html AS.1.7]]" <<AS>> as 1424
1421 --> 1424
rectangle "[[Requirements-EHRSFMR2.1-AS.8.3.html AS.8.3]]" <<AS>> as 1651
rectangle "[[Requirements-EHRSFMR2.1-AS.9.3.html AS.9.3]]" <<AS>> as 1685
1651 --> 1685
rectangle "[[Requirements-EHRSFMR2.1-AS.1.5.html AS.1.5#03]]" <<AS>> as 1417
1417 -[dotted]-> 2559
rectangle "[[Requirements-EHRSFMR2.1-AS.1.5.html AS.1.5#04]]" <<AS>> as 1418
1418 -[dotted]-> 1424
rectangle "[[Requirements-EHRSFMR2.1-AS.9.3.html AS.9.3#06]]" <<AS>> as 1691
1691 -[dotted]-> 437
rectangle "[[Requirements-EHRSFMR2.1-POP.2.1.html POP.2.1]]" <<POP>> as 1286
rectangle "[[Requirements-EHRSFMR2.1-TI.5.3.html TI.5.3]]" <<TI>> as 2622
1286 --> 2622
rectangle "[[Requirements-EHRSFMR2.1-POP.2.2.html POP.2.2]]" <<POP>> as 1299
1299 --> 2622
rectangle "[[Requirements-EHRSFMR2.1-POP.2.3.html POP.2.3]]" <<POP>> as 1306
1306 --> 2559
rectangle "[[Requirements-EHRSFMR2.1-POP.8.html POP.8]]" <<POP>> as 1370
rectangle "[[Requirements-EHRSFMR2.1-TI.1.8.html TI.1.8]]" <<TI>> as 2247
1370 --> 2247
rectangle "[[Requirements-EHRSFMR2.1-POP.9.html POP.9]]" <<POP>> as 1377
1377 --> 846
rectangle "[[Requirements-EHRSFMR2.1-CPS.9.4.html CPS.9.4]]" <<CPS>> as 1228
1377 --> 1228
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.html RI.1.1]]" <<RI>> as 1704
rectangle "[[Requirements-EHRSFMR2.1-RI.1.2.1.html RI.1.2.1]]" <<RI>> as 2120
1704 --> 2120
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.4.html RI.1.1.4]]" <<RI>> as 1772
rectangle "[[Requirements-EHRSFMR2.1-TI.1.1.html TI.1.1]]" <<TI>> as 2195
1772 --> 2195
rectangle "[[Requirements-EHRSFMR2.1-TI.1.2.html TI.1.2]]" <<TI>> as 2208
1772 --> 2208
rectangle "[[Requirements-EHRSFMR2.1-RI.1.3.1.html RI.1.3.1]]" <<RI>> as 2149
1772 --> 2149
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.6.html RI.1.1.6]]" <<RI>> as 1815
rectangle "[[Requirements-EHRSFMR2.1-TI.1.6.html TI.1.6]]" <<TI>> as 2236
1815 --> 2236
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.13.html RI.1.1.13]]" <<RI>> as 1944
1815 --> 1944
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.10.html RI.1.1.10]]" <<RI>> as 1907
1815 --> 1907
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.7.html RI.1.1.7]]" <<RI>> as 1838
1838 --> 2236
1838 --> 1944
1838 --> 1907
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.8.html RI.1.1.8]]" <<RI>> as 1859
1859 --> 2236
1859 --> 1944
1859 --> 1907
1944 --> 1907
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.14.html RI.1.1.14]]" <<RI>> as 1966
rectangle "[[Requirements-EHRSFMR2.1-RI.3.html RI.3]]" <<RI>> as 2185
1966 --> 2185
2120 --> 1704
2120 --> 1772
rectangle "[[Requirements-EHRSFMR2.1-RI.1.2.2.html RI.1.2.2]]" <<RI>> as 2140
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.23.html RI.1.1.23]]" <<RI>> as 2092
2140 --> 2092
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.24.html RI.1.1.24]]" <<RI>> as 2107
2140 --> 2107
2140 --> 1944
rectangle "[[Requirements-EHRSFMR2.1-TI.2.1.1.html TI.2.1.1]]" <<TI>> as 2283
2149 --> 2283
rectangle "[[Requirements-EHRSFMR2.1-RI.1.3.2.html RI.1.3.2]]" <<RI>> as 2157
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.2.html RI.1.1.2]]" <<RI>> as 1736
2157 --> 1736
rectangle "[[Requirements-EHRSFMR2.1-RI.1.1.2.1.html RI.1.1.2.1]]" <<RI>> as 1741
2157 --> 1741
2157 --> 2120
rectangle "[[Requirements-EHRSFMR2.1-RI.1.3.4.html RI.1.3.4]]" <<RI>> as 2168
2168 --> 2014
rectangle "[[Requirements-EHRSFMR2.1-RI.2.html RI.2]]" <<RI>> as 2179
rectangle "[[Requirements-EHRSFMR2.1-TI.5.1.html TI.5.1]]" <<TI>> as 2602
2179 --> 2602
2179 --> 2559
rectangle "[[Requirements-EHRSFMR2.1-RI.1.3.html RI.1.3]]" <<RI>> as 2148
1966 -[dotted]-> 2148
rectangle "[[Requirements-EHRSFMR2.1-TI.2.html TI.2]]" <<TI>> as 2274
2208 --> 2274
rectangle "[[Requirements-EHRSFMR2.1-TI.1.3.html TI.1.3]]" <<TI>> as 2214
2214 --> 2195
2214 --> 2208
rectangle "[[Requirements-EHRSFMR2.1-TI.1.4.html TI.1.4]]" <<TI>> as 2228
2228 --> 2214
2228 --> 2208
2231 --> 2274
2231 --> 1772
rectangle "[[Requirements-EHRSFMR2.1-TI.1.7.html TI.1.7]]" <<TI>> as 2244
2236 --> 2244
2244 --> 2195
2244 --> 2274
2247 --> 2195
2247 --> 2208
2247 --> 2214
2247 --> 2231
2247 --> 2236
2247 --> 2274
2274 --> 2214
rectangle "[[Requirements-EHRSFMR2.1-TI.2.1.html TI.2.1]]" <<TI>> as 2277
2277 --> 2277
rectangle "[[Requirements-EHRSFMR2.1-RI.1.html RI.1]]" <<RI>> as 1703
2283 --> 1703
2559 --> 2602
rectangle "[[Requirements-EHRSFMR2.1-TI.5.1.1.html TI.5.1.1]]" <<TI>> as 2603
rectangle "[[Requirements-EHRSFMR2.1-TI.4.html TI.4]]" <<TI>> as 2571
2603 --> 2571
rectangle "[[Requirements-EHRSFMR2.1-TI.5.4.html TI.5.4]]" <<TI>> as 2625
2625 --> 2559
@enduml
